# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

localRegression <- function(weightmat, modelmat, xtemp) {
    .Call(`_RSEE_localRegression`, weightmat, modelmat, xtemp)
}

iterLowess <- function(weightX, weightY, modelmat, x, h, smoothpara, epsmed = 10^(-6)) {
    .Call(`_RSEE_iterLowess`, weightX, weightY, modelmat, x, h, smoothpara, epsmed)
}

lastIterLowess <- function(weightX, weightY, modelmat, x, h) {
    .Call(`_RSEE_lastIterLowess`, weightX, weightY, modelmat, x, h)
}

